[workspace]

members = [
    "convert",
    "fib",
    "owner",
    "rc",
    "refCell",
    "life",
    "type_system",
    "trait_exam",
    "arc",
    "mystring",
    "mymap",
    "closure",
    "kv",
    "cs"
]

