[package]
name = "sea_orm_common"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { version = "1.1.3", features = ["debug-print", "runtime-tokio-native-tls", "sqlx-mysql"] }
chrono = "0.4.38"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"